config/routes.rb
Rails.application.routes.draw do
  root to: 'photos#index'
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }  

  resources :photos, only: [:index, :show]

  namespace :admin do
    resources :photos do
      post :positions, on: :collection
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/common/uuid.rb
module Common
  module Uuid
    extend ActiveSupport::Concern

    included do
      validates :uuid, uniqueness: true

      before_validation :generate_uuid, on: :create

      private

      def generate_uuid(opts={})
        if uuid.blank? || opts[:force] == true
          self.uuid = loop do
            # these uuid-lengths were chosen not very rigorously to balance
            # the total number space with minimizing the
            # number of DB collision checks that are likely to
            # be performed in the generation of a single uuid.
            # A reference table for the number space can be found here:
            # http://thestarman.pcministry.com/asm/6to64bits.htm
            if !defined?(uuid_length)
              _min_uuid_length = defined?(min_uuid_length) ? min_uuid_length : 2

              count_or_1 = self.class.count == 0 ? 1 : self.class.count
              
              # min length is 2:
              uuid_length = [(Math.log((count_or_1 * 4), 16)/2).ceil, _min_uuid_length].max
            end

            random_uuid = SecureRandom.hex(uuid_length)

            # puts "generated UUID for #{self.class}: #{random_uuid}"

            base_scope  = persisted? ? self.class.where.not(id: id) : self.class.all

            break random_uuid if base_scope.where(uuid: random_uuid).size == 0
          end
        end

        true
      end
    end
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  include Common::Uuid
  extend FriendlyId
  
  mount_uploader :image, ImageUploader

  friendly_id :uuid

  belongs_to :user

  validates :image, presence: true

  before_create :set_default_position

  scope :visible, ->{ where.not(hidden: true) }
  scope :by_position, ->{ order(position: :desc) }

  private

  def set_default_position
    self.position ||= Photo.count
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :photos
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout 'admin'

  before_action :require_login

  def require_login
    unless current_user
      flash[:notice] = "You must be logged in to access this page"
   
      redirect_to new_user_session_path(next: request.path) and return
    end    
  end
end

app/controllers/admin/photos_controller.rb
class Admin::PhotosController < Admin::BaseController
  handles_sortable_columns

  before_action :find_photo, only: member_actions

  def index
    @photos = current_user.photos.order(sortable_column_order || 'position DESC').page(params[:page]).per(50)
  end

  def new
  end

  def create
    @photos = []
    
    params[:image_files].each do |image_file|        
      @photo = current_user.photos.new(
        image: image_file
      )

      if @photo.save
        @photos << @photo
      end
    end

    render json: {
      files: @photos.map { |photo|
        {
          id: photo.id,
          name: photo.image.filename,
          size: photo.image.file.size,
          url: photo.image.url,
          thumbnailUrl: photo.image.url(:thumbnail),
          deleteUrl: admin_photo_path(photo),
          deleteType: 'DELETE'
        }
      }
    }

  end
  
  def show
  end

  def edit
  end

  def update
    if @photo.update(photo_params)
      redirect_to edit_admin_photo_path(@photo), notice: 'Photo settings saved'
    else
      render :edit
    end
  end

  def positions
    if params[:positions].present?
      mappings = []
      # note, unintuitively, each VALUE here is actually a hash of the form {id: "id", position: "position"}
      params[:positions].each_pair do |k, v|
        mappings << {id: v["id"], position: v["position"]}
      end

      for item in mappings
        @photo = current_user.photos.find(item[:id])
        @photo.update!(position: item[:position])
      end
    end

    render json: { status: :success }
  end

  def destroy
    @photo.destroy
    
    respond_to do |format|
      format.json { head :no_content }
      format.html { redirect_to admin_photos_path, notice: 'Photo successfully deleted' }
    end
  end

  private

  def find_photo
    @photo = current_user.photos.friendly.find(params[:id])
  end

  def photo_params
    params.fetch(:photo, {}).permit(:hidden, :title, :caption, :description, :position)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  
  protect_from_forgery with: :exception

  helper_method :render_to_string

  def self.member_actions(*extras)
    [:show, :edit, :update, :destroy] + extras
  end

  def self.collection_actions(*extras)
    [:index, :new, :create] + extras
  end  
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :find_photo, only: :show

  def index
    @photos = Photo.visible.by_position.page(params[:page]).per(50)
  end

  def show
  end

  private

  def find_photo
    @photo = Photo.visible.friendly.find(params[:id])
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  skip_before_action :require_no_authentication

# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   result = super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def controller?(*controller)
    controller.include?(params[:controller])
  end

  def action?(*action)
    action.include?(params[:action])
  end

  def alerts(options={})
    render_to_string(:partial => "/common/alerts", locals: options).html_safe
  end

  def base_errors(record, *extras)
    extras = extras || []
    render_to_string(:partial => "/common/base_errors", locals: {record: record, extras: extras}).html_safe
  end

  # for kaminari bootstrap views:
  # https://github.com/matenia/bootstrap-kaminari-views
  def paginate(objects, options = {})
    options.reverse_merge!( theme: 'twitter-bootstrap-3' )

    content_tag :div, class: 'pagination-wrap' do
      super( objects, options )
    end
  end

  def site_config
    Rails.application.config.site_config
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
  def next_photo_for(photo)
    @next_photo ||= Photo.visible
                         .where.not(id: photo.id)
                         .where("position < ?", photo.position)
                         .order(position: :desc)
                         .first
  end

  def prev_photo_for(photo)
    @prev_photo ||= Photo.visible
                         .where.not(id: photo.id)
                         .where("position > ?", photo.position)
                         .order(position: :asc)
                         .first
  end
end

app/views/admin/photos/_photo.haml
- cache ['admin', photo] do
  %li.photo-wrap.js-photo-wrap{data: {id: photo.id}}
    = link_to edit_admin_photo_path(photo), class: 'thumbnail photo' do
      = image_tag photo.image.url(:preview)

app/views/admin/photos/edit.haml
.row
  .col-md-8.col-md-offset-2
    = simple_form_for [:admin, @photo] do |f|
      .thumbnail.thumbnail-large
        = image_tag @photo.image.xl

      = f.input :title, as: :string
      = f.input :caption, as: :string
      = f.input :description
      = f.input :hidden, as: :boolean, label: 'Hide this photo'
      = f.input :position
      - if site_config[:display_dates]
        = f.input :display_date

      = f.button :submit, "Save Settings", class: 'btn btn-default pull-right'

      = link_to nil, href: admin_photo_path(@photo),
      data: {confirm: "Are you sure you want to delete this photo?", method: :delete}, class: "delete-link" do
        %i.fa.fa-trash-o
        Delete Photo
        
      .clearfix

app/views/admin/photos/index.haml
%nav.navbar.admin-nav.navbar-inverse
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#admin-nav-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      
    #admin-nav-collapse.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li{class: ('active' if controller?('admin/photos'))}
          = link_to new_admin_photo_path do
            Upload Photos

%ul.admin-photos-grid.js-admin-photos-grid.list-unstyled
  = render @photos

.clearfix

.pagination-wrap.text-center
  = paginate @photos  

:coffee
  window.base_image_position = #{@photos.first.try(:position)}
  window.position_update_url = '#{positions_admin_photos_path(format: :json)}'

  $ -> new App.Views.Admin.Photos.Index                    

app/views/admin/photos/new.haml
.bulk-image-upload-page
  .col-md-12
    .panel.panel-default
      .panel-heading
        Upload Photos
      .panel-body
        = form_tag admin_photos_path, id: 'fileupload' do    
          %p
            Click the "Add Files" button below to select files in your file browser. Alternatively you can drag and drop files onto this page.
          .spacer
          .row.fileupload-buttonbar
            .col-md-7
              %span.btn.btn-success.fileinput-button
                %i.fa.fa-plus
                %span.text Add files
                = file_field_tag 'image_files[]', class: 'file-input js-image-file-input', multiple: true

              %button.btn.btn-primary.start{type: 'submit'}
                %i.fa.fa-cloud-upload
                %span.text Upload All

              %button.btn.btn-warning.cancel{type: 'reset'}
                %i.fa.fa-ban
                %span.text Cancel Upload

              %button.btn.btn-danger.delete
                %i.fa.fa-trash
                %span.text Delete

            .col-md-5.col-lg-5.fileupload-progress.fade
              / The global progress bar
              .progress.progress-striped.active{"aria-valuemax" => "100", "aria-valuemin" => "0", :role => "progressbar"}
                .progress-bar.progress-bar-success{:style => "width:0%;"}
              / The extended global progress state
              .progress-extended &nbsp;
          
          / The table listing the files available for upload/download
          %table.table.table-striped.js-image-table.bulk-upload-table{:role => "presentation"}
            %tbody.files                            

:coffee
   $ -> new App.Views.Admin.Photos.New

-# template files read by jquery.fileupload-ui (https://blueimp.github.io/jQuery-File-Upload/)
:plain
  <script id="template-upload" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
      <tr class="template-upload fade">
          <td>
              <span class="preview"></span>
          </td>
          <td>
              <p class="name">{%=file.name%}</p>
              <strong class="error text-danger"></strong>
          </td>
          <td>
              <p class="size">Processing...</p>
              <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
          </td>
          <td>
              {% if (!i && !o.options.autoUpload) { %}
                  <button class="btn btn-primary start" disabled>
                      <i class="glyphicon glyphicon-upload"></i>
                      <span>Start</span>
                  </button>
              {% } %}
              {% if (!i) { %}
                  <button class="btn btn-warning cancel">
                      <i class="glyphicon glyphicon-ban-circle"></i>
                      <span>Cancel</span>
                  </button>
              {% } %}
          </td>
      </tr>
  {% } %}
  </script>
  <!-- The template to display files available for download -->
  <script id="template-download" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
      <tr class="template-download fade" 
          {% if (file.thumbnailUrl) { %} data-id='{%= file.id %}' {% } %}>
          <td>
              <span class="preview">
                  {% if (file.thumbnailUrl) { %}
                      <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery><img src="{%=file.thumbnailUrl%}"></a>
                  {% } %}
              </span>
          </td>
          <td>
              <p class="name">
                  {% if (file.url) { %}
                      <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" {%=file.thumbnailUrl?'data-gallery':''%}>{%=file.name%}</a>
                  {% } else { %}
                      <span>{%=file.name%}</span>
                  {% } %}
              </p>
              {% if (file.error) { %}
                  <div><span class="label label-danger">Error</span> {%=file.error%}</div>
              {% } %}
          </td>
          <td>
              <span class="size">{%=o.formatFileSize(file.size)%}</span>
          </td>
          <td>
              {% if (file.deleteUrl) { %}
                  <button class="btn btn-danger delete" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}"{% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}>
                      <i class="glyphicon glyphicon-trash"></i>
                      <span>Delete</span>
                  </button>
                  <input type="checkbox" name="delete" value="1" class="toggle">
              {% } else { %}
                  <button class="btn btn-warning cancel">
                      <i class="glyphicon glyphicon-ban-circle"></i>
                      <span>Cancel</span>
                  </button>
              {% } %}
          </td>
      </tr>
  {% } %}
  </script>       

app/views/common/_alerts.haml
-if flash and flash[:notice].present?
  .alert.alert-success.flash
    %a{:class => 'close', :data => {:dismiss => 'alert', :target => ".alert-row"}}
      &times;
    .inner-text
      = flash[:notice]

-if flash and flash[:alert].present?
  .alert.alert-danger.flash
    %a{:class => 'close', :data => {:dismiss => 'alert', :target => ".alert-row"}}
      &times;
    .inner-text
      = flash[:alert]

-if flash and flash[:warning].present?
  .alert.alert-danger.flash
    %a{:class => 'close', :data => {:dismiss => 'alert', :target => ".alert-row"}}
      &times;
    .inner-text
      = flash[:warning]

-if flash and flash[:validation_errors].present?
  .alert.alert-danger.flash.validation-errors
    %a{:class => 'close', :data => {:dismiss => 'alert', :target => ".alert-row"}}
      &times;
    .inner-text
      = flash[:validation_errors]

app/views/common/_fonts.html.erb
<link href="https://fonts.googleapis.com/css?family=Lato:300,300i,400,400i,700,900" rel="stylesheet">

app/views/common/_navbar.haml
%nav.navbar.main-nav
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#primary-nav-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand.z-logo{:href => root_path} 
        Photostream

    - if user_signed_in?
      #primary-nav-collapse.collapse.navbar-collapse
        %ul.nav.navbar-nav

        %ul.nav.navbar-nav.navbar-right
          %li{class: ('active' if controller?('admin/photos'))}
            = link_to admin_photos_path do
              %i.fa.fa-camera.icon
              Manage Photos
          %li
            = link_to "Sign Out", destroy_user_session_path, method: :delete              

app/views/layouts/admin.haml
- @_body_classes ||= []
- @_body_classes << 'layout-admin'

- content_for :head do
  = javascript_include_tag 'admin'
  = stylesheet_link_tag 'admin'

- content_for :content do
  - if content_for? :admin_content
    = yield :admin_content
  - else
    = yield

= render template: '/layouts/application'

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{name: "viewport", content: "initial-scale=1,width=device-width,minimum-scale=1.0, maximum-scale=1.0,user-scalable=no"}
    %title Photostream
    = csrf_meta_tags
    = render 'common/fonts'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    - if content_for? :head
      = yield :head
  %body{class: "#{params[:controller].split('/').join(' ')} #{params[:action]}#{@_body_classes ? (' ' + @_body_classes.join(' ')) : ''}"}
    = render 'common/navbar'
    .container.main-container
      = alerts

      - if content_for? :content
        = yield :content
      - else
        = yield

    - if content_for? :outside_container
      = yield :outside_container

    #footer.footer.text-center
      :plain
        Site made with ZPhotostream - fork the project <a href="https://github.com/nzaillian/zphotostream" target="_blank">here</a>!

app/views/photos/_photo.haml
- cache photo do
  = link_to photo, class: 'photo col-sm-6 no-pad', id: "photo_#{photo.id}" do
    = image_tag photo.image.url(:preview)

app/views/photos/index.haml
- cache @photos do
  .photos
    - @photos.in_groups_of(2, false) do |group|
      .row
        = render group

  .pagination-wrap.text-center
    = paginate @photos

app/views/photos/show.haml
- content_for :outside_container do
  - cache [Photo.maximum(:updated_at), @photo, 'links'] do
    - if prev_photo_for(@photo)
      = link_to prev_photo_for(@photo), class: 'carousel-link prev js-prev-photo-link' do
        %i.fa.fa-chevron-left.icon

    - if next_photo_for(@photo)
      = link_to next_photo_for(@photo), class: 'carousel-link next js-next-photo-link' do
        %i.fa.fa-chevron-right.icon

- cache [Photo.maximum(:updated_at), @photo, 'photo'] do
  .photo-detail-page
    .photo-detail-box
      = link_to '', @photo.image.url, class: 'photo-detail-link', target: '_blank', style: "background-image: url(#{@photo.image.url(:xxl)});", data: {"photo-id" => @photo.id}

    .photo-meta
      - if @photo.caption.present?
        .photo-caption= raw @photo.caption
      - if @photo.description.present?
        .photo-description= raw @photo.description        
      - if site_config[:display_dates] && @photo.display_date.present?
        .photo-display-date
          %span.uploaded Uploaded
          %span.date= "#{@photo.display_date.strftime(site_config[:display_date_format])}"

:coffee
  $ -> new App.Views.Photos.Show    

app/views/users/shared/_links.html.haml
- extra_opts = {}

.login-links.text-center
  - if controller_name != 'sessions'
    = link_to "Sign In to Existing Account", new_session_path(resource_name, extra_opts)
    %br

  -# - if devise_mapping.registerable? && controller_name != 'registrations'
  -#   -# = link_to "Register a new account", new_registration_path(resource_name, extra_opts)
  -#   = link_to "Register a new account", new_user_registration_path
  -#   %br

  - if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
    = link_to "Forgot your password?", new_password_path(resource_name, extra_opts)
    %br

  - if devise_mapping.confirmable? && controller_name != 'confirmations'
    = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name, extra_opts)
    %br

  - if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
    = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name, extra_opts)
    %br

  - if devise_mapping.omniauthable?
    - resource_class.omniauth_providers.each do |provider|
      = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider, extra_opts)
      %br